default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tavern_on_rails_development

test:
  <<: *default
  database: tavern_on_rails_test

production:
  primary: &primary_production
    <<: *default
    database: tavern_on_rails_production
    username: tavern_on_rails
    password: <%= ENV["TAVERN_ON_RAILS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tavern_on_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tavern_on_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tavern_on_rails_production_cable
    migrations_paths: db/cable_migrate
